# Generated by Django 4.1.7 on 2023-03-05 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipesapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='name',
            new_name='recipe',
        ),
        migrations.RenameField(
            model_name='useringredient',
            old_name='name',
            new_name='ingredient',
        ),
    ]
