# Generated by Django 4.0.10 on 2023-03-05 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipesapi', '0002_rename_name_recipe_recipe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='description',
            field=models.TextField(default='No description available'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='url',
            field=models.URLField(default='No url available'),
        ),
    ]
